# Generated by Django 5.0.7 on 2024-08-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='carapp.carmodel'),
        ),
    ]
